import { ICharClass } from '../models/dbModels/ICharClass';
import { EEquipment } from './dbEquipmentProficiencies';
import { ESkills } from './dbSkills';

export enum ECharClasses {
  Barbarian = 'ccl01',
  Bard = 'ccl02',
  Cleric = 'ccl03',
  Druid = 'ccl04',
  Fighter = 'ccl05',
  Monk = 'ccl06',
  Paladin = 'ccl07',
  Ranger = 'ccl08',
  Rogue = 'ccl09',
  Sorcerer = 'ccl10',
  Warlock = 'ccl11',
  Wizard = 'ccl12',
}

export const charClasses: ICharClass[] = [
  {
    id: 'ccl01',
    name: 'Barbarian',
    desc: `The strong embrace the wild that hides inside - keen instincts, primal physicality, and most of all, an unbridled, unquenchable rage.`,
    icon: './icons/charClasses/Barbarian_Icon.png',
    casterLevelPerLevel: 0,
    subclassAtLevel: 3,
    subclasses: ['scl01', 'scl02', 'scl03'],
    skillProficiencies: [
      ESkills.AnimalHandling,
      ESkills.Athletics,
      ESkills.Intimidation,
      ESkills.Nature,
      ESkills.Survival,
      ESkills.Perception,
    ],
    skillProficiencySlots: 2,
    armorProficiencies: [EEquipment.LightArmor, EEquipment.MediumArmor, EEquipment.Shields],
    weaponProficiencies: [EEquipment.SimpleW, EEquipment.MartialW],
  },
  {
    id: 'ccl02',
    name: 'Bard',
    desc: `Bards know music is more than idle fancy - it is power. Through study and adventure, these travelling troubadours master song, speech, and the magic within.`,
    icon: './icons/charClasses/Bard_Icon.png',
    casterLevelPerLevel: 1,
    cantripsKnown: [
      { fromLevel: 1, amount: 2 },
      { fromLevel: 4, amount: 3 },
      { fromLevel: 10, amount: 4 },
    ],
    spellsOnStartingLevel: 4,
    spellsPerLevel: 1,
    subclassAtLevel: 3,
    subclasses: ['scl04', 'scl05', 'scl06'],
    expertiseAtLevel: 3,
    skillExpertiseSlots: 2,
    skillProficiencies: [
      ESkills.Acrobatics,
      ESkills.AnimalHandling,
      ESkills.Arcana,
      ESkills.Athletics,
      ESkills.Deception,
      ESkills.History,
      ESkills.Insight,
      ESkills.Intimidation,
      ESkills.Investigation,
      ESkills.Medicine,
      ESkills.Nature,
      ESkills.Perception,
      ESkills.Performance,
      ESkills.Persuasion,
      ESkills.Religion,
      ESkills.SleightOfHand,
      ESkills.Stealth,
      ESkills.Survival,
    ],
    skillProficiencySlots: 3,
    armorProficiencies: [EEquipment.LightArmor],
    weaponProficiencies: [
      EEquipment.SimpleW,
      EEquipment.HandCrossbows,
      EEquipment.Rapiers,
      EEquipment.Longswords,
      EEquipment.Shortswords,
    ],
  },
  {
    id: 'ccl03',
    name: 'Cleric',
    desc: `Clerics are representatives of the gods they worship, wielding potent divine magic for good or ill`,
    icon: './icons/charClasses/Cleric_Icon.png',
    casterLevelPerLevel: 1,
    cantripsKnown: [
      { fromLevel: 1, amount: 3 },
      { fromLevel: 4, amount: 4 },
      { fromLevel: 10, amount: 5 },
    ],
    subclassAtLevel: 1,
    subclasses: ['scl07', 'scl08', 'scl09', 'scl10', 'scl11', 'scl12', 'scl13'],
    skillProficiencies: [ESkills.History, ESkills.Insight, ESkills.Medicine, ESkills.Persuasion, ESkills.Religion],
    skillProficiencySlots: 2,
    armorProficiencies: [EEquipment.LightArmor, EEquipment.MediumArmor, EEquipment.Shields],
    weaponProficiencies: [EEquipment.SimpleW, EEquipment.Flails, EEquipment.Morningstars],
  },
  {
    id: 'ccl04',
    name: 'Druid',
    desc: `Druids channel the elemental forces of nature and share a deep kinship with animals. Mastery of Wild Shape allows them to transform into beasts from all over the Realms.`,
    icon: './icons/charClasses/Druid_Icon.png',
    casterLevelPerLevel: 1,
    cantripsKnown: [
      { fromLevel: 1, amount: 2 },
      { fromLevel: 4, amount: 3 },
      { fromLevel: 10, amount: 4 },
    ],
    subclassAtLevel: 2,
    subclasses: ['scl14', 'scl15', 'scl46'],
    skillProficiencies: [
      ESkills.Arcana,
      ESkills.AnimalHandling,
      ESkills.Insight,
      ESkills.Medicine,
      ESkills.Nature,
      ESkills.Perception,
      ESkills.Religion,
      ESkills.Survival,
    ],
    skillProficiencySlots: 2,
    armorProficiencies: [EEquipment.LightArmor, EEquipment.MediumArmor, EEquipment.Shields],
    weaponProficiencies: [
      EEquipment.Clubs,
      EEquipment.Daggers,
      EEquipment.Javelins,
      EEquipment.Maces,
      EEquipment.Quarterstaves,
      EEquipment.Scimitars,
      EEquipment.Sickles,
      EEquipment.Spears,
    ],
  },
  {
    id: 'ccl05',
    name: 'Fighter',
    desc: `Fighters have mastered the art of combat, wielding weapons with unmatched skill and wearing armour like a second skin.`,
    icon: './icons/charClasses/Fighter_Icon.png',
    casterLevelPerLevel: 0,
    subclassAtLevel: 3,
    subclasses: ['scl16', 'scl17', 'scl18'],
    skillProficiencies: [
      ESkills.Acrobatics,
      ESkills.AnimalHandling,
      ESkills.Athletics,
      ESkills.History,
      ESkills.Insight,
      ESkills.Intimidation,
      ESkills.Perception,
      ESkills.Survival,
    ],
    skillProficiencySlots: 2,
    armorProficiencies: [EEquipment.LightArmor, EEquipment.MediumArmor, EEquipment.HeavyArmor, EEquipment.Shields],
    weaponProficiencies: [EEquipment.SimpleW, EEquipment.MartialW],
  },
  {
    id: 'ccl06',
    name: 'Monk',
    desc: `Some reach enlightenment by languid meditation - others do so in the heat of battle. Monks manipulate ki to empower their own strikes and debilitate their foes.`,
    icon: './icons/charClasses/Monk_Icon.png',
    casterLevelPerLevel: 0,
    subclassAtLevel: 3,
    subclasses: ['scl19', 'scl20', 'scl21'],
    skillProficiencies: [
      ESkills.Acrobatics,
      ESkills.Athletics,
      ESkills.History,
      ESkills.Insight,
      ESkills.Religion,
      ESkills.Stealth,
    ],
    skillProficiencySlots: 2,
    armorProficiencies: [],
    weaponProficiencies: [EEquipment.SimpleW, EEquipment.Shortswords],
  },
  {
    id: 'ccl07',
    name: 'Paladin',
    desc: `A promise made so deeply that it becomes divine in itself flows through a paladin, burning bright enough to inspire allies and smite foes.`,
    icon: './icons/charClasses/Paladin_Icon.png',
    casterLevelPerLevel: 0.5,
    subclassAtLevel: 1,
    subclasses: ['scl22', 'scl23', 'scl24', 'scl25'],
    skillProficiencies: [
      ESkills.Athletics,
      ESkills.Insight,
      ESkills.Intimidation,
      ESkills.Medicine,
      ESkills.Persuasion,
      ESkills.Religion,
    ],
    skillProficiencySlots: 2,
    armorProficiencies: [EEquipment.LightArmor, EEquipment.MediumArmor, EEquipment.HeavyArmor, EEquipment.Shields],
    weaponProficiencies: [EEquipment.SimpleW, EEquipment.MartialW],
  },
  {
    id: 'ccl08',
    name: 'Ranger',
    desc: `Rangers are unrivalled scouts and trackers, honing a deep connection with nature in order to hunt their favoured prey.`,
    icon: './icons/charClasses/Ranger_Icon.png',
    casterLevelPerLevel: 0.5,
    spellsOnStartingLevel: 2,
    spellsPerLevel: 0.5,
    subclassAtLevel: 3,
    subclasses: ['scl26', 'scl27', 'scl28'],
    skillProficiencies: [
      ESkills.AnimalHandling,
      ESkills.Athletics,
      ESkills.Insight,
      ESkills.Investigation,
      ESkills.Nature,
      ESkills.Perception,
      ESkills.Stealth,
      ESkills.Survival,
    ],
    skillProficiencySlots: 3,
    armorProficiencies: [EEquipment.LightArmor, EEquipment.MediumArmor, EEquipment.Shields],
    weaponProficiencies: [EEquipment.SimpleW, EEquipment.MartialW],
  },
  {
    id: 'ccl09',
    name: 'Rogue',
    desc: `With stealth, skill, and uncanny reflexes, rogues' versatility lets them get the upper hand in almost any situation.`,
    icon: './icons/charClasses/Rogue_Icon.png',
    casterLevelPerLevel: 0,
    subclassAtLevel: 3,
    subclasses: ['scl29', 'scl30', 'scl31'],
    expertiseAtLevel: 1,
    skillExpertiseSlots: 2,
    skillProficiencies: [
      ESkills.Acrobatics,
      ESkills.Athletics,
      ESkills.Deception,
      ESkills.Insight,
      ESkills.Investigation,
      ESkills.Perception,
      ESkills.Performance,
      ESkills.Persuasion,
      ESkills.SleightOfHand,
      ESkills.Stealth,
    ],
    skillProficiencySlots: 4,
    armorProficiencies: [EEquipment.LightArmor],
    weaponProficiencies: [
      EEquipment.SimpleW,
      EEquipment.HandCrossbows,
      EEquipment.Longswords,
      EEquipment.Rapiers,
      EEquipment.Shortswords,
    ],
  },
  {
    id: 'ccl10',
    name: 'Sorcerer',
    desc: `Sorcerers are natural spellcasters, drawing on inherent magic from a gift or bloodline.`,
    icon: './icons/charClasses/Sorcerer_Icon.png',
    casterLevelPerLevel: 1,
    cantripsKnown: [
      { fromLevel: 1, amount: 4 },
      { fromLevel: 4, amount: 5 },
      { fromLevel: 10, amount: 6 },
    ],
    spellsOnStartingLevel: 2,
    spellsPerLevel: 1,
    subclassAtLevel: 1,
    subclasses: ['scl32', 'scl33', 'scl34'],
    skillProficiencies: [
      ESkills.Arcana,
      ESkills.Deception,
      ESkills.Insight,
      ESkills.Intimidation,
      ESkills.Persuasion,
      ESkills.Religion,
    ],
    skillProficiencySlots: 2,
    armorProficiencies: [],
    weaponProficiencies: [EEquipment.Daggers, EEquipment.Quarterstaves, EEquipment.LightCrossbows],
  },
  {
    id: 'ccl11',
    name: 'Warlock',
    desc: `Bound by a pact to an all-powerful patron, warlocks trade their loyalty for supernatural abilities and unique magic.`,
    icon: './icons/charClasses/Warlock_Icon.png',
    casterLevelPerLevel: 0,
    cantripsKnown: [
      { fromLevel: 1, amount: 2 },
      { fromLevel: 4, amount: 3 },
      { fromLevel: 10, amount: 4 },
    ],
    spellsOnStartingLevel: 2,
    spellsPerLevel: 1,
    subclassAtLevel: 1,
    subclasses: ['scl35', 'scl36', 'scl37'],
    skillProficiencies: [
      ESkills.Arcana,
      ESkills.Deception,
      ESkills.History,
      ESkills.Intimidation,
      ESkills.Investigation,
      ESkills.Nature,
      ESkills.Religion,
    ],
    skillProficiencySlots: 2,
    armorProficiencies: [EEquipment.LightArmor],
    weaponProficiencies: [EEquipment.SimpleW],
  },
  {
    id: 'ccl12',
    name: 'Wizard',
    desc: `Wizards master the arcane by specialising in individual schools of magic, combining ancient spells with modern research.`,
    icon: './icons/charClasses/Wizard_Icon.png',
    casterLevelPerLevel: 1,
    cantripsKnown: [
      { fromLevel: 1, amount: 3 },
      { fromLevel: 4, amount: 4 },
      { fromLevel: 10, amount: 5 },
    ],
    spellsOnStartingLevel: 6,
    spellsPerLevel: 2,
    subclassAtLevel: 2,
    subclasses: ['scl38', 'scl39', 'scl40', 'scl41', 'scl42', 'scl43', 'scl44', 'scl45'],
    skillProficiencies: [
      ESkills.Arcana,
      ESkills.History,
      ESkills.Investigation,
      ESkills.Insight,
      ESkills.Medicine,
      ESkills.Religion,
    ],
    skillProficiencySlots: 2,
    armorProficiencies: [],
    weaponProficiencies: [EEquipment.Daggers, EEquipment.Quarterstaves, EEquipment.LightCrossbows],
  },
];
