import { ISpell } from '../models/dbModels/ISpell';

export const lvl1spells: ISpell[] = [
  {
    id: 'spl101',
    name: 'Animal Friendship',
    desc: 'Convince a beast not to attack you. The creature must have an Intelligence of 3 or less. Condition ends early if you or an ally hurts the target. In higher difficulty modes, the target might become hostile when the spell ends.',
    school: 'Enchantment',
    details: [`Cost: Action + Level 1 Spell Slot`, `WIS Save, Range: 18m / 60ft`],
    icon: './icons/lvl1spells/Animal_Friendship.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl04', 'ccl18'],
  },
  {
    id: 'spl102',
    name: 'Armour of Agathys',
    desc: 'Gain 5 temporary hit points and deal 5 Cold damage to any creature that hits you with a melee attack.',
    school: 'Abjuration',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: Self`],
    icon: './icons/lvl1spells/Armour_of_Agathys.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl11'],
  },
  {
    id: 'spl103',
    name: 'Arms of Hadar',
    desc: 'Prevent targets from using reactions.',
    school: 'Conjuration',
    details: [
      `Cost: Action + Level 1 Spell Slot`,
      `Damage  2d6 Necrotic`,
      `STR Save (On Save: Targets still take half damage but are able to use Reactions.)`,
      `Range: Self, AoE: 3m / 10ft (Radius)`,
    ],
    icon: './icons/lvl1spells/Arms_of_Hadar.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl11'],
  },
  {
    id: 'spl104',
    name: 'Bane',
    desc: 'Up to 3 creatures receive a -1d4 penalty to Attack rolls and Saving throws.',
    school: 'Enchantment',
    details: [`Cost: Action + Level 1 Spell Slot`, `CHA Save`, `Range: 9m / 30ft`],
    icon: './icons/lvl1spells/Bane.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl02', 'ccl03'],
  },
  {
    id: 'spl105',
    name: 'Bless',
    desc: 'Bless up to 3 creatures. They gain a +1d4 bonus to Attack rolls and Saving throws.',
    school: 'Enchantment',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: 9m / 30ft`],
    icon: './icons/lvl1spells/Bless.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl03'],
  },
  {
    id: 'spl106',
    name: 'Burning Hands',
    desc: 'Each flammable target is hit with 3d6 Fire damage.',
    school: 'Evocation',
    details: [
      `Cost: Action + Level 1 Spell Slot`,
      'Damage: 3d6 Fire (DEX save to halve)',
      `Range:  AoE: 5m / 17ft (Cone)`,
    ],
    icon: './icons/lvl1spells/Burning_Hands.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl10', 'ccl11', 'scl35'],
  },
  {
    id: 'spl107',
    name: 'Charm Person',
    desc: 'Charm a humanoid to prevent it from attacking you. You gain Advantage on Charisma Checks in dialogue. Enemies have Advantage on Saving throws against being Charmed. Condition ends early if you or an ally hurts the target. In higher difficulty modes, the target might accuse you of enchanting them.',
    school: 'Enchantment',
    details: [`Cost: Action + Level 1 Spell Slot`, 'WIS Save', `Range:   18m / 60ft`],
    icon: './icons/lvl1spells/Charm_Person.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl04', 'ccl10', 'ccl11', 'ccl12'],
  },
  {
    id: 'spl108',
    name: 'Chromatic Orb',
    desc: 'Hurl a sphere of energy. It deals 3d8 Thunder damage, or 2d8 Acid, Cold, Fire, Lightning or Poison damage and creates a surface.',
    school: 'Evocation',
    details: [`Cost: Action + Level 1 Spell Slot`, 'Attack Roll', `Range:   18m / 60ft`],
    icon: './icons/lvl1spells/Chromatic_Orb.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl10', 'ccl12'],
  },
  {
    id: 'spl109',
    name: 'Colour Spray',
    desc: 'Blind creatures up to a combined 33 Hit Points.',
    school: 'Illusion',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: AoE: 5m / 15ft (Cone)`],
    icon: './icons/lvl1spells/Colour_Spray.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl10', 'ccl12'],
  },
  {
    id: 'spl110',
    name: 'Command',
    desc: 'Command a creature to flee, move closer, freeze, drop to the ground or drop its weapon. The target must succeed on a  Wisdom saving throw in order to resist the effects.',
    school: 'Enchantment',
    details: [`Cost: Action + Level 1 Spell Slot`, `WIS Save`, `Range: 18m / 60ft`],
    icon: './icons/lvl1spells/Command.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl03', 'ccl07', 'scl35'],
  },
  {
    id: 'spl111',
    name: 'Compelled Duel',
    desc: 'Force an enemy to attack only you, giving it Disadvantage against other targets.',
    school: 'Enchantment',
    details: [`Cost: Bonus action + Level 1 Spell Slot`, `WIS Save`, `Range: 18m / 60ft`],
    icon: './icons/lvl1spells/Compelled_Duel.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl07'],
  },
  {
    id: 'spl112',
    name: 'Create or Destroy Water',
    desc: 'Choose to call forth rain or destroy a water-based surface.',
    school: 'Transmutation',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: 9m / 30ft`, ` AoE: 4m / 13ft (Radius)`],
    icon: './icons/lvl1spells/Create_Water.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl03', 'ccl04'],
  },
  {
    id: 'spl113',
    name: 'Cure Wounds',
    desc: 'Heal a creature you can touch. No effect on undead and constructs.',
    school: 'Evocation',
    details: [
      `Cost: Action + Level 1 Spell Slot`,
      `Healing: 1d8 + Spellcasting modifier hit points`,
      `Range: 1.5m / 5ft`,
    ],
    icon: './icons/lvl1spells/Cure_Wounds.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl03', 'ccl04', 'ccl07', 'ccl08'],
  },
  {
    id: 'spl114',
    name: 'Disguise Self',
    desc: 'Magically change all aspects of your appearance.',
    school: 'Illusion',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: Self`],
    icon: './icons/lvl1spells/Disguise_Self.png',
    spellLevel: 1,
    isRitual: true,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl10', 'ccl12'],
  },
  {
    id: 'spl115',
    name: 'Dissonant Whispers',
    desc: `Frighten a creature: they'll have Disadvantage on  Ability checks and Attack rolls and they cannot move.`,
    school: 'Enchantment',
    details: [
      `Cost: Action + Level 1 Spell Slot`,
      `Damage: 3d6 Psychic`,
      `WIS Save (On Save: Targets still take half damage.)`,
      `Range: 18m / 60ft`,
    ],
    icon: './icons/lvl1spells/Dissonant_Whispers.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl02', 'scl36'],
  },
  {
    id: 'spl116',
    name: 'Divine Favour',
    desc: `Your prayer empowers you with divine radiance. Your weapons deal an additional 1d4 Radiant damage.`,
    school: 'Evocation',
    details: [`Cost: Bonus action + Level 1 Spell Slot`, `Range: Self`],
    icon: './icons/lvl1spells/Divine_Favour.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl07'],
  },
  {
    id: 'spl117',
    name: 'Enhance Leap',
    desc: `Triple a creature's Jumping distance.`,
    school: 'Transmutation',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: 1.5m / 5 ft`],
    icon: './icons/lvl1spells/Enhance_Leap.png',
    spellLevel: 1,
    isRitual: true,
    hasConcentration: false,
    availableTo: ['ccl04', 'ccl10', 'ccl12', 'ccl08'],
  },
  {
    id: 'spl118',
    name: 'Ensnaring Strike',
    desc: `Your attack summons thorny vines, dealing Weapon Damage and possibly Ensnaring your target.Ensnared creatures cannot move and take 1d6 Piercing damage at the start of each turn. An ally can use their Help Action to try and tear away the vines.`,
    school: 'Conjuration',
    details: [`Cost: Action. On Hit: Bonus Action + Level 1 Spell Slot`, `Attack Roll, STR save`],
    icon: './icons/lvl1spells/Ensnaring_Strike.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl08'],
  },
  {
    id: 'spl119',
    name: 'Entangle',
    desc: `Vines sprout from the ground, turning it into Difficult Terrain and possibly Entangling creatures within. Entangled creatures cannot move. An ally can use its help action to try and tear away the vines.`,
    school: 'Conjuration',
    details: [
      `Cost: Action + Level 1 Spell Slot`,
      `STR save`,
      `Range: 18m / 60ft, AoE: 3m / 10ft (Radius)`,
      `Creates Area: Twisting Vines`,
    ],
    icon: './icons/lvl1spells/Entangle.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl04'],
  },
  {
    id: 'spl120',
    name: 'Expeditious Retreat',
    desc: `Gain Dash immediately and as a bonus action on each of your turns until this spell ends.`,
    school: 'Transmutation',
    details: [`Cost: Bonus action + Level 1 Spell Slot`, `Range: Self`],
    icon: './icons/lvl1spells/Expeditious_Retreat.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl10', 'ccl11', 'ccl12'],
  },
  {
    id: 'spl121',
    name: 'Faerie Fire',
    desc: `All targets within the light turn visible, and Attack rolls against them have Advantage.`,
    school: 'Evocation',
    details: [`Cost: Action + Level 1 Spell Slot`, `DEX Save`, ` Range: 18m / 60ft. AoE: 6m / 20ft (Radius)`],
    icon: './icons/lvl1spells/Faerie_Fire.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl02', 'ccl04', 'scl37'],
  },
  {
    id: 'spl122',
    name: 'False Life',
    desc: `Bolster yourself with a necromantic facsimile of life to gain 7 temporary hit points. Can only have temporary hit points from one source.`,
    school: 'Necromancy',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: Self`],
    icon: './icons/lvl1spells/False_Life.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl12', 'ccl10'],
  },
  {
    id: 'spl123',
    name: 'Feather Fall',
    desc: `You and nearby allies gain Immunity to Falling damage.`,
    school: 'Transmutation',
    details: [`Cost: Bonus action + Level 1 Spell Slot`, ` Range: Self. AoE: 9m / 30ft (Radius)`],
    icon: './icons/lvl1spells/Feather_Fall.png',
    spellLevel: 1,
    isRitual: true,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl12', 'ccl10'],
  },
  {
    id: 'spl124',
    name: 'Find Familiar',
    desc: `Summon a familiar, a fey spirit that takes an animal form of your choosing`,
    school: 'Conjuration',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: 18m / 60ft`, `Recharge: Short rest`],
    icon: './icons/lvl1spells/Find_Familiar.png',
    spellLevel: 1,
    isRitual: true,
    hasConcentration: false,
    availableTo: ['ccl12'],
  },
  {
    id: 'spl125',
    name: 'Fog Cloud',
    desc: `Create a cloud of dense fog to Heavily Obscure and Blind creatures within.`,
    school: 'Conjuration',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: 18m / 60ft. AoE: 5m / 15ft (Radius)`, `Creates Area: Fog`],
    icon: './icons/lvl1spells/Fog_Cloud.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl04', 'ccl10', 'ccl12', 'ccl08'],
  },
  {
    id: 'spl126',
    name: 'Goodberry',
    desc: `Conjure four magical berries for yourself or a companion. Creatures who eat a berry regain 1d4 hit points. Each berry counts as one Camp Supplies. The berries appear in the targeted creature's inventory and disappear after a Long Rest.`,
    school: 'Transmutation',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: 1.5m / 5ft`],
    icon: './icons/lvl1spells/Goodberry.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl04', 'ccl08'],
  },
  {
    id: 'spl127',
    name: 'Grease',
    desc: `Cover the ground in flammable grease. It becomes Difficult Terrain and creatures within can fall Prone.`,
    school: 'Conjuration',
    details: [`Cost: Action + Level 1 Spell Slot`, `DEX Save`, `Range: 18m / 60ft`, `Creates Area: Grease`],
    icon: './icons/lvl1spells/Grease.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl10'],
  },
  {
    id: 'spl128',
    name: 'Guiding Bolt',
    desc: `The next attack roll against this target has Advantage.`,
    school: 'Evocation',
    details: [`Cost: Action + Level 1 Spell Slot`, `Damage: 4d6 Radiant`, `Attack Roll`, `Range: 18m / 60ft`],
    icon: './icons/lvl1spells/Guiding_Bolt.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl03'],
  },
  {
    id: 'spl129',
    name: 'Hail of Thorns',
    desc: `Shoot a volley of thorns. The thorns deal weapon damage to the target and then explode. The explosion deals an additional 1d10 Piercing damage to the target and surrounding creatures. On miss, the thorns still explode. On save, targets still take half damage from the explosion.`,
    school: 'Conjuration',
    details: [
      `Cost: Action + Bonus Action + Level 1 Spell Slot`,
      `Damage: Normal weapon damage + 1d10 Piercing (DEX save to halve)`,
      `Attack Roll (On Miss: Thorns still explode.)`,
      `Range: 18m / 60ft. AoE: 2m / 7ft (Radius)`,
    ],
    icon: './icons/lvl1spells/Hail_of_Thorns.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl08'],
  },
  {
    id: 'spl130',
    name: 'Healing Word',
    desc: `Heal a creature you can see. No effect on undead and constructs.`,
    school: 'Evocation',
    details: [
      `Cost: Bonus Action + Level 1 Spell Slot`,
      `Healing: 1d4 + Spellcasting modifier hit points`,
      `Range: 18m / 60ft`,
    ],
    icon: './icons/lvl1spells/Healing_Word.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl03', 'ccl04'],
  },
  {
    id: 'spl131',
    name: 'Hellish Rebuke',
    desc: `React to your next attacker with flames that deal 2d10 Fire damage.On a successful save, the target still takes half damage.`,
    school: 'Evocation',
    details: [`Cost: Reaction + Level 1 Spell Slot`, `Damage: 2d10 Fire (Dexterity save to halve)`],
    icon: './icons/lvl1spells/Hellish_Rebuke.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl11'],
  },
  {
    id: 'spl132',
    name: 'Heroism',
    desc: `Make yourself or a target immune to Frightened and gain 5 Temporary Hit Points each turn. Can only have Temporary Hit Points from one source.`,
    school: 'Enchantment',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: 1.5m / 5ft`],
    icon: './icons/lvl1spells/Heroism.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl02', 'ccl07'],
  },
  {
    id: 'spl133',
    name: 'Hex',
    desc: `Make your attacks deal an additional 1d6 Necrotic damage to the target and give it Disadvantage on an Ability of your choosing. If the target dies before the spell ends, you can Reapply Hex to a new creature without expending a Spell Slot.`,
    school: 'Enchantment',
    details: [`Cost: Bonus Action + Level 1 Spell Slot`, `Damage: 1d6 Necrotic (conditional)`, `Range: 18m / 60ft`],
    icon: './icons/lvl1spells/Hex.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl11'],
  },
  {
    id: 'spl134',
    name: `Hunter's Mark`,
    desc: `Mark a creature as your quarry to deal an additional 1d6 Weapon damage whenever you hit it with a weapon attack. If the target dies before the spell ends, you can use Reapply Hunter's Mark to mark a new creature.`,
    school: 'Divination',
    details: [`Cost: Bonus Action + Level 1 Spell Slot`, `Damage: 1d6 Physical (conditional)`, `Range: 18m / 60ft`],
    icon: './icons/lvl1spells/Hunters_Mark.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl08'],
  },
  {
    id: 'spl135',
    name: `Ice Knife`,
    desc: `Throw a shard of ice that deals 1d10 Piercing damage. It explodes and deals 2d6 Cold damage to anyone nearby. It leaves an Ice surface. On miss, the shard of ice still explodes. This spell can be cast while you are  Silenced.`,
    school: 'Conjuration',
    details: [
      `Cost: Action + Level 1 Spell Slot`,
      `Damage: 1d10 Piercing+ 2d6 Cold`,
      `Attack roll (On Miss: The shard of ice still explodes.)`,
      `DEX Save (On Save: The damage from the explosion is negated)`,
      `Range: 18m / 60ft. AoE: 2m / 7ft (Radius)`,
      `Creates Area: Ice`,
    ],
    icon: './icons/lvl1spells/Ice_Knife.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl04', 'ccl10', 'ccl12'],
  },
  {
    id: 'spl136',
    name: `Inflict Wounds`,
    desc: `Putrefy a creature with Necrotic energy filling your hands.`,
    school: 'Necromancy',
    details: [`Cost: Action + Level 1 Spell Slot`, `Damage: 3d10 Necrotic`, `Attack roll `, `Range: 1.5m / 5ft`],
    icon: './icons/lvl1spells/Inflict_Wounds.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl03'],
  },
  {
    id: 'spl137',
    name: `Longstrider`,
    desc: `Increase a creature's Movement Speed by  3m / 10ft.`,
    school: 'Transmutation',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: 1.5m / 5ft`],
    icon: './icons/lvl1spells/Longstrider.png',
    spellLevel: 1,
    isRitual: true,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl04', 'ccl12', 'ccl08'],
  },
  {
    id: 'spl138',
    name: `Mage Armour`,
    desc: `Surround an unarmoured creature in a protective magical force. Its Armour Class increases to 13 + its Dexterity modifier. The target can't be wearing Armour.`,
    school: 'Abjuration',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: 1.5m / 5ft`],
    icon: './icons/lvl1spells/Mage_Armour.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl12', 'ccl10'],
  },
  {
    id: 'spl139',
    name: `Magic Missile`,
    desc: `Create three darts of magical force, each dealing 1d4 + 1 Force damage to its target. The darts always hit their target, and can each be targeted individually.`,
    school: 'Evocation',
    details: [`Cost: Action + Level 1 Spell Slot`, `Damage: 1d4 + 1 Force per dart`, `Range: 18m / 60ft`],
    icon: './icons/lvl1spells/Magic_Missile.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl12', 'ccl10'],
  },
  {
    id: 'spl140',
    name: `Protection from Evil and Good`,
    desc: `Protect an ally against the attacks and powers of Aberrations, Celestials, Elementals, Fey, Fiends, and Undead. The targets can't be Charmed,  Frightened, or possessed by them, and when these creatures attack it, they have Disadvantage.`,
    school: 'Abjuration',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: 1.5m / 5ft`],
    icon: './icons/lvl1spells/Protection.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl12', 'ccl11', 'ccl03', 'ccl07'],
  },
  {
    id: 'spl141',
    name: `Ray of Sickness`,
    desc: `Possibly  Poisons the target.`,
    school: 'Necromancy',
    details: [`Cost: Action + Level 1 Spell Slot`, `Damage: 2d8 Poison`, `Attack Roll, CON Save`, `Range: 18m / 60ft`],
    icon: './icons/lvl1spells/Ray_of_Sickness.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl12', 'ccl10'],
  },
  {
    id: 'spl142',
    name: `Sanctuary`,
    desc: `You or an ally cannot be targeted until you attack or harm a creature. You can still take damage from area spells. Until the affected entity attacks or harms another creature, it cannot be targeted by enemy attacks. However, it can still take damage from spells that influence a larger area.`,
    school: 'Abjuration',
    details: [`Cost: Bonus Action + Level 1 Spell Slot`, `Range: 18m / 60ft`],
    icon: './icons/lvl1spells/Sanctuary.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl03'],
  },
  {
    id: 'spl143',
    name: `Searing Smite`,
    desc: `Your weapon flares with white-hot intensity. It deals, on top of weapon damage, an extra 1d6D Fire damage and marks the target with Searing Smite.`,
    school: 'Evocation',
    details: [
      `Cost: Action. Cost on Hit: Bonus Action + Level 1 Spell Slot`,
      `Damage: Normal weapon damage +  1d6 Fire + 1d6 Fire per turn`,
      `Attack Roll`,
      `Range: Normal weapon range`,
    ],
    icon: './icons/lvl1spells/Searing_Smite.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl07'],
  },
  {
    id: 'spl144',
    name: `Shield`,
    desc: `When you are about to be hit by an enemy, use your Reaction to increase your Armour Class by 5. You also take no damage from Magic Missile. These effects last until the start of your next turn.`,
    school: 'Abjuration',
    details: [`Cost: Reaction + Level 1 Spell Slot`, `Range: Self`],
    icon: './icons/lvl1spells/Shield.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl10', 'ccl12'],
  },
  {
    id: 'spl145',
    name: `Shield of Faith`,
    desc: `Surround a creature with a shimmering field of magic that increases its Armour Class by 2.`,
    school: 'Abjuration',
    details: [`Cost: Bonus Action + Level 1 Spell Slot`, `Range: 18m / 60ft`],
    icon: './icons/lvl1spells/Shield_of_Faith.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl03', 'ccl08'],
  },
  {
    id: 'spl146',
    name: `Sleep`,
    desc: `Put creatures into a magical slumber. Select targets up to a combined 24 Hit Points. The condition ends upon taking damage.`,
    school: 'Enchantment',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: 18m / 60ft`],
    icon: './icons/lvl1spells/Sleep.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl10', 'ccl12', 'scl37'],
  },
  {
    id: 'spl147',
    name: `Speak with Animals`,
    desc: `Gain the ability to comprehend and communicate with beasts`,
    school: 'Divination',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: Self`],
    icon: './icons/lvl1spells/Speak_with_Animals.png',
    spellLevel: 1,
    isRitual: true,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl04', 'ccl08'],
  },
  {
    id: 'spl148',
    name: `Tasha's Hideous Laughter`,
    desc: `Leave a creature  Prone with laughter, without the ability to get up. The creature must have an Intelligence of 5 or more. The target can try to shake off the effect each time it takes damage.`,
    school: 'Enchantment',
    details: [`Cost: Action + Level 1 Spell Slot`, `WIS Save (Spell save DC)`, `Range: 18m / 60ft`],
    icon: './icons/lvl1spells/Tasha.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl02', 'ccl12', 'scl36'],
  },
  {
    id: 'spl149',
    name: `Thunderous Smite`,
    desc: `Your melee weapon rings with thunder as you strike, pushing your target  3m / 10ft away and possibly knocking them Prone.`,
    school: 'Evocation',
    details: [
      `Cost: Action. Cost on Hit: Bonus Action + Level 1 Spell Slot`,
      `Damage: Normal weapon damage +  2d6 Thunder`,
      `Attack Roll, STR Save (Spell save DC) (On Save: Target takes full damage but isn't knocked Prone)`,
      `Range: Normal weapon range`,
    ],
    icon: './icons/lvl1spells/Thunderous_Smite.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl07'],
  },
  {
    id: 'spl150',
    name: `Thunderwave`,
    desc: `Release a wave of thunderous force that pushes away all creatures and objects in an area, while also dealing Thunder damage.`,
    school: 'Evocation',
    details: [
      `Cost: Action + Level 1 Spell Slot`,
      `Damage: 2d8 Thunder (CON save to halve)`,
      `CON Save (On Save: Targets take half damage; aren't pushed away.)`,
      `Range: 1.5m / 5ft. AoE: 5m / 17ft (Cube)`,
    ],
    icon: './icons/lvl1spells/Thunderwave.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl04', 'ccl10', 'ccl12'],
  },
  {
    id: 'spl151',
    name: `Witch Bolt`,
    desc: `Link yourself to a target with a bolt of lightning. Deal an additional 1d12 Lightning each turn by activating it.`,
    school: 'Evocation',
    details: [`Cost: Action + Level 1 Spell Slot`, `Damage: 1d12 Lightning`, `Attack Roll`, `Range: 18m / 60ft`],
    icon: './icons/lvl1spells/Witch_Bolt.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl11', 'ccl10', 'ccl12'],
  },
  {
    id: 'spl152',
    name: `Wrathful Smite`,
    desc: `Your weapon absorbs your wrath as you strike, possibly  Frightening your target.`,
    school: 'Evocation',
    details: [
      `Cost: Action. Cost on Hit: Bonus Action + Level 1 Spell Slot`,
      `Damage: Normal weapon damage +  1d6 Psychic`,
      `Attack Roll, WIS Save)`,
      `Range: Normal weapon range`,
    ],
    icon: './icons/lvl1spells/Wrathful_Smite.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl07'],
  },
];
