import { ISpell } from '../models/dbModels/ISpell';

export const lvl1spells: ISpell[] = [
  {
    id: 'spl101',
    name: 'Animal Friendship',
    desc: 'Convince a beast not to attack you. The creature must have an Intelligence of 3 or less. Condition ends early if you or an ally hurts the target. In higher difficulty modes, the target might become hostile when the spell ends.',
    school: 'Enchantment',
    details: [`Cost: Action + Level 1 Spell Slot`, `WIS Save, Range: 18m / 60ft`],
    icon: './icons/lvl1spells/Animal_Friendship.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl04', 'ccl18'],
  },
  {
    id: 'spl102',
    name: 'Armour of Agathys',
    desc: 'Gain 5 temporary hit points and deal 5 Cold damage to any creature that hits you with a melee attack.',
    school: 'Abjuration',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: Self`],
    icon: './icons/lvl1spells/Armour_of_Agathys.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl11'],
  },
  {
    id: 'spl103',
    name: 'Arms of Hadar',
    desc: 'Prevent targets from using reactions.',
    school: 'Conjuration',
    details: [
      `Cost: Action + Level 1 Spell Slot`,
      `Damage  2d6 Necrotic`,
      `STR Save (On Save: Targets still take half damage but are able to use Reactions.)`,
      `Range: Self, AoE: 3m / 10ft (Radius)`,
    ],
    icon: './icons/lvl1spells/Arms_of_Hadar.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl11'],
  },
  {
    id: 'spl104',
    name: 'Bane',
    desc: 'Up to 3 creatures receive a -1d4 penalty to Attack rolls and Saving throws.',
    school: 'Enchantment',
    details: [`Cost: Action + Level 1 Spell Slot`, `CHA Save`, `Range: 9m / 30ft`],
    icon: './icons/lvl1spells/Bane.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl02', 'ccl03'],
  },
  {
    id: 'spl105',
    name: 'Bless',
    desc: 'Bless up to 3 creatures. They gain a +1d4 bonus to Attack rolls and Saving throws.',
    school: 'Enchantment',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: 9m / 30ft`],
    icon: './icons/lvl1spells/Bless.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl03'],
  },
  {
    id: 'spl106',
    name: 'Burning Hands',
    desc: 'Each flammable target is hit with 3d6 Fire damage.',
    school: 'Evocation',
    details: [
      `Cost: Action + Level 1 Spell Slot`,
      'Damage: 3d6 Fire (DEX save to halve)',
      `Range:  AoE: 5m / 17ft (Cone)`,
    ],
    icon: './icons/lvl1spells/Burning_Hands.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl10', 'ccl11', 'scl35'],
  },
  {
    id: 'spl107',
    name: 'Charm Person',
    desc: 'Charm a humanoid to prevent it from attacking you. You gain Advantage on Charisma Checks in dialogue. Enemies have Advantage on Saving throws against being Charmed. Condition ends early if you or an ally hurts the target. In higher difficulty modes, the target might accuse you of enchanting them.',
    school: 'Enchantment',
    details: [`Cost: Action + Level 1 Spell Slot`, 'WIS Save', `Range:   18m / 60ft`],
    icon: './icons/lvl1spells/Charm_Person.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl04', 'ccl10', 'ccl11', 'ccl12'],
  },
  {
    id: 'spl108',
    name: 'Chromatic Orb',
    desc: 'Hurl a sphere of energy. It deals 3d8 Thunder damage, or 2d8 Acid, Cold, Fire, Lightning or Poison damage and creates a surface.',
    school: 'Evocation',
    details: [`Cost: Action + Level 1 Spell Slot`, 'Attack Roll', `Range:   18m / 60ft`],
    icon: './icons/lvl1spells/Chromatic_Orb.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl10', 'ccl12'],
  },
  {
    id: 'spl109',
    name: 'Colour Spray',
    desc: 'Blind creatures up to a combined 33 Hit Points.',
    school: 'Illusion',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: AoE: 5m / 15ft (Cone)`],
    icon: './icons/lvl1spells/Colour_Spray.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl10', 'ccl12'],
  },
  {
    id: 'spl110',
    name: 'Command',
    desc: 'Command a creature to flee, move closer, freeze, drop to the ground or drop its weapon. The target must succeed on a  Wisdom saving throw in order to resist the effects.',
    school: 'Enchantment',
    details: [`Cost: Action + Level 1 Spell Slot`, `WIS Save`, `Range: 18m / 60ft`],
    icon: './icons/lvl1spells/Command.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl03', 'ccl07', 'scl35'],
  },
  {
    id: 'spl111',
    name: 'Compelled Duel',
    desc: 'Force an enemy to attack only you, giving it Disadvantage against other targets.',
    school: 'Enchantment',
    details: [`Cost: Bonus action + Level 1 Spell Slot`, `WIS Save`, `Range: 18m / 60ft`],
    icon: './icons/lvl1spells/Compelled_Duel.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl07'],
  },
  {
    id: 'spl112',
    name: 'Create or Destroy Water',
    desc: 'Choose to call forth rain or destroy a water-based surface.',
    school: 'Transmutation',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: 9m / 30ft`, ` AoE: 4m / 13ft (Radius)`],
    icon: './icons/lvl1spells/Create_Water.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl03', 'ccl04'],
  },
  {
    id: 'spl113',
    name: 'Cure Wounds',
    desc: 'Heal a creature you can touch. No effect on undead and constructs.',
    school: 'Evocation',
    details: [
      `Cost: Action + Level 1 Spell Slot`,
      `Healing: 1d8 + Spellcasting modifier hit points`,
      `Range: 1.5m / 5ft`,
    ],
    icon: './icons/lvl1spells/Cure_Wounds.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl03', 'ccl04', 'ccl07', 'ccl08'],
  },
  {
    id: 'spl114',
    name: 'Disguise Self',
    desc: 'Magically change all aspects of your appearance.',
    school: 'Illusion',
    details: [`Cost: Action + Level 1 Spell Slot`, `Range: Self`],
    icon: './icons/lvl1spells/Disguise_Self.png',
    spellLevel: 1,
    isRitual: true,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl10', 'ccl12'],
  },
  {
    id: 'spl115',
    name: 'Dissonant Whispers',
    desc: `Frighten a creature: they'll have Disadvantage on  Ability checks and Attack rolls and they cannot move.`,
    school: 'Enchantment',
    details: [
      `Cost: Action + Level 1 Spell Slot`,
      `Damage: 3d6 Psychic`,
      `WIS Save (On Save: Targets still take half damage.)`,
      `Range: 18m / 60ft`,
    ],
    icon: './icons/lvl1spells/Dissonant_Whispers.png',
    spellLevel: 1,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl02', 'scl36'],
  },
];
