import { ISpell } from '../models/dbModels/ISpell';

export const lvl0spells: ISpell[] = [
  {
    id: 'spl001',
    name: 'Acid Splash',
    desc: 'Throw a bubble of acid that damages each creature it hits.',
    school: 'Conjuration',
    details: [`Damage: 1d6 Acid (DEX save to negate)`, `DEX Save, Range: 18m / 60ft AoE: 2m / 7ft (Radius)`],
    icon: './icons/lvl0spells/Acid_Splash.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl10', 'ccl12', 'scl17', 'scl30'],
  },
  {
    id: 'spl002',
    name: 'Blade Ward',
    desc: 'Take only half the damage from Bludgeoning,Piercing, and Slashing attacks.',
    school: 'Abjuration',
    details: [`Range: Self`],
    icon: './icons/lvl0spells/Blade_Ward.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl03', 'ccl10', 'ccl11', 'ccl12', 'scl17', 'scl30'],
  },
  {
    id: 'spl003',
    name: 'Bone Chill',
    desc: 'Prevent the target from healing until your next turn. An undead target receives Disadvantage on Attack rolls.',
    school: 'Necromancy',
    details: [`Damage: 1d8 Necrotic`, `Attack roll, Range: 18m / 60ft`],
    icon: './icons/lvl0spells/Bone_Chill.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl10', 'ccl11', 'ccl12', 'scl17', 'scl30'],
  },
  {
    id: 'spl004',
    name: 'Dancing Lights',
    desc: 'Illuminate a  9m / 30ft radius.',
    school: 'Evocation',
    details: [`Range: 18m / 60ft, AoE: 9m / 30ft (Radius)`],
    icon: './icons/lvl0spells/Dancing_Lights.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl02', 'ccl10', 'ccl12', 'scl17', 'scl30'],
  },
  {
    id: 'spl005',
    name: 'Eldritch Blast',
    desc: 'Conjure a beam of crackling energy. Deals 1d10 Force damage to a target.',
    school: 'Evocation',
    details: [`Damage: 1d10 Force`, `Attack roll,  Range: 18m / 60ft`],
    icon: './icons/lvl0spells/Eldritch_Blast.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl11'],
  },
  {
    id: 'spl006',
    name: 'Fire Bolt',
    desc: 'Hurl a mote of fire.',
    school: 'Evocation',
    details: [`Damage: 1d10 Fire`, `Attack roll,  Range: 18m / 60ft`],
    icon: './icons/lvl0spells/Fire_Bolt.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl10', 'ccl12', 'scl17', 'scl30'],
  },
  {
    id: 'spl007',
    name: 'Friends',
    desc: `Gain Advantage on Charisma Checks against a non-hostile creature. This spell can be cast while you are Silenced. In higher difficulty modes, the target might accuse you of enchanting them. Duration: 10 turns`,
    school: 'Enchantment',
    details: [`Range: 18m / 60ft`],
    icon: './icons/lvl0spells/Friends.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl02', 'ccl10', 'ccl11', 'ccl12', 'scl17', 'scl30'],
  },
  {
    id: 'spl008',
    name: 'Guidance',
    desc: `The target gains +1d4 bonus to  Ability checks. Duration: 10 turns`,
    school: 'Divination',
    details: [`Range: 1.5m / 5 ft`],
    icon: './icons/lvl0spells/Guidance.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl03', 'ccl04'],
  },
  {
    id: 'spl009',
    name: 'Light',
    desc: `Infuse an object with an aura of light. Only affects one target at a time.`,
    school: 'Evocation',
    details: [`Range: 1.5m / 5 ft`],
    icon: './icons/lvl0spells/Light.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl10', 'ccl03', 'ccl12', 'scl17', 'scl30'],
  },
  {
    id: 'spl010',
    name: 'Mage Hand',
    desc: `Create a spectral hand that can manipulate and interact with objects. Duration: 10 turns. This cantrip can only be cast once per short rest`,
    school: 'Conjuration',
    details: [`Range: 18m / 60ft`, `Recharge: Short rest`],
    icon: './icons/lvl0spells/Mage_Hand.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl10', 'ccl11', 'ccl12', 'scl17', 'scl30'],
  },
  {
    id: 'spl011',
    name: 'Minor Illusion',
    desc: `Create an illusion that compels nearby creatures to investigate. You can remain hidden while casting this spell. This spell can be cast while you are Silenced.`,
    school: 'Illusion',
    details: [`Range: 18m / 60ft`],
    icon: './icons/lvl0spells/Minor_Illusion.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl02', 'ccl10', 'ccl11', 'ccl12', 'scl17', 'scl30', 'scl21'],
  },
  {
    id: 'spl012',
    name: 'Poison Spray',
    desc: `Project a puff of noxious gas, dealing 1d12 Poison to a target.`,
    school: 'Conjuration',
    details: [`Damage: 1d12 Poison (CON save to negate)`, `Range: 3m / 10ft`],
    icon: './icons/lvl0spells/Poison_Spray.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl04', 'ccl10', 'ccl11', 'ccl12', 'scl17', 'scl30'],
  },
  {
    id: 'spl013',
    name: 'Produce Flame',
    desc: `A flame in your hand sheds a light in a  9m / 30ft radius and deals 1d8 Fire damage when thrown.Throwing the flame immediately after you conjure it does not cost an Action. Extinguishing or throwing it on subsequent turns costs an Action. The throw has a range of  9m / 30ft.`,
    school: 'Conjuration',
    details: [`Range: Self`],
    icon: './icons/lvl0spells/Produce_Flame.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl03', 'ccl04'],
  },
  {
    id: 'spl014',
    name: 'Ray of Frost',
    desc: `Reduces the target's Movement Speed by  3m / 10ft.`,
    school: 'Evocation',
    details: [`Damage: 1d8 Cold (Attack Roll)`, `Range: 18m / 60ft`],
    icon: './icons/lvl0spells/Ray_of_Frost.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl10', 'ccl12', 'scl17', 'scl30'],
  },
  {
    id: 'spl015',
    name: 'Resistance',
    desc: `Make a target more resistant to spell effects and conditions: it receives a +1d4 bonus to Saving throws.`,
    school: 'Abjuration',
    details: [`Range: 1.5m / 5 ft`],
    icon: './icons/lvl0spells/Resistance.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl03', 'ccl04'],
  },
  {
    id: 'spl016',
    name: 'Sacred Flame',
    desc: `Engulf a target in a flame-like radiance.`,
    school: 'Evocation',
    details: [`Damage: 1d8 Radiant (DEX save to negate)`, `Range: 18m / 60ft`],
    icon: './icons/lvl0spells/Sacred_Flame.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl03'],
  },
  {
    id: 'spl017',
    name: 'Shillelagh',
    desc: `Quarterstaff or Club Required. Your staff or club becomes magical: it deals 1d8 + Wisdom Modifier Bludgeoning damage, and uses your Spellcasting Ability for Attack rolls.`,
    school: 'Transmutation',
    details: [`Cost: Bonus action`, `Range: Self`],
    icon: './icons/lvl0spells/Shillelagh.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl04'],
  },
  {
    id: 'spl018',
    name: 'Shocking Grasp',
    desc: `The target cannot use Reactions. This spell has Advantage on creatures with metal Armour.`,
    school: 'Evocation',
    details: [`Damage: 1d8 Lightning (Attack Roll)`, `Range: 1.5m / 5 ft`],
    icon: './icons/lvl0spells/Shocking_Grasp.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl10', 'ccl12', 'scl17', 'scl30'],
  },
  {
    id: 'spl019',
    name: 'Thaumaturgy',
    desc: `Gain Advantage on Intimidation and Performance Checks.`,
    school: 'Transmutation',
    details: [`Range: Self`],
    icon: './icons/lvl0spells/Thaumaturgy.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl03'],
  },
  {
    id: 'spl020',
    name: 'Thorn Whip',
    desc: `Pulls the creature  3m / 10ft closer to you. The target cannot be pulled if it is Huge in size.`,
    school: 'Transmutation',
    details: [`Melee spell attack roll`, `Range:  9m / 30ft`],
    icon: './icons/lvl0spells/Thorn_Whip.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl04'],
  },
  {
    id: 'spl021',
    name: 'True Strike',
    desc: `Gain Advantage on your next Attack roll.`,
    school: 'Divination',
    details: [`Melee spell attack roll`, `Range:  18m / 60ft`],
    icon: './icons/lvl0spells/True_Strike.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: true,
    availableTo: ['ccl02', 'ccl10', 'ccl11', 'ccl12', 'scl17', 'scl30'],
  },
  {
    id: 'spl022',
    name: 'Vicious Mockery',
    desc: `Insult a creature: it has Disadvantage on its next Attack roll.`,
    school: 'Enchantment',
    details: [`Damage: 1d4 Psychic (WIS save to negate)`, `Range:  18m / 60ft`],
    icon: './icons/lvl0spells/Vicious_Mockery.png',
    spellLevel: 0,
    isRitual: false,
    hasConcentration: false,
    availableTo: ['ccl02'],
  },
];
