import { IOrigin } from '../models/dbModels/IOrigin';
import { ECharBg } from './dbCharBackgrounds';
import { ECharClasses } from './dbCharClasses';
import { ESubClasses } from './dbSubClass';
import { ESubraces } from './dbSubraces';

export const dbOrigins: IOrigin[] = [
  {
    id: 'ori01',
    name: 'Custom',
    desc: `You’ve always felt you had a greater calling, but it has never borne fruit. Everything changes when you awaken imprisoned on an alien ship. Perhaps your time has finally come.`,
    icon: './icons/origins/cus_icon.png',
    defaultRace: '',
    defaultClass: ECharClasses.Barbarian,
  },
  {
    id: 'ori02',
    name: 'Astarion',
    desc: `Astarion prowled the night as a vampire spawn for centuries, forced to follow the orders of his sadistic master, Cazador: seduce every fool with a pulse, and lure them back to Cazador's lair. Free for now, Astarion will do anything to keep his life in the light. He can see but one way to ensure his liberty for good: become many times more powerful than his old abuser could ever dream of being. His body is forever tainted by the intricate, patterned scarring Cazador carved upon his back, and the elder vampire seems set on sending out waves of hunters seeking to capture his lost spawn.`,
    icon: './icons/origins/ast_icon.png',
    backgroundId: ECharBg.Charlatan,
    defaultRace: '',
    defaultSubrace: ESubraces.HighElf,
    defaultClass: ECharClasses.Rogue,
  },
  {
    id: 'ori03',
    name: 'Gale',
    desc: `Gale of Waterdeep was a prodigious archmage, his talents earning him the attention of Mystra, the goddess of magic. At her side, he learned all that mortals might accomplish with the Weave, in time earning his place as her lover, and her Chosen. And yet, he was not satisfied. In an attempt to prove he was ready for even greater power, he accidentally unleashed 'the orb' - a highly volatile fragment of pure Weave, corrupted by Netherese magic, which buried itself in his chest. Cast out by Mystra, humbled by his downfall, he does all he can to prevent the orb's cataclysmic detonation, watching for his chance to get back everything he lost, and more.`,
    icon: './icons/origins/gal_icon.png',
    backgroundId: ECharBg.Sage,
    defaultRace: '',
    defaultClass: ECharClasses.Wizard,
  },
  {
    id: 'ori04',
    name: 'Karlach',
    desc: `Gale of Waterdeep was a prodigious archmage, his talents earning him the attention of Mystra, the goddess of magic. At her side, he learned all that mortals might accomplish with the Weave, in time earning his place as her lover, and her Chosen. And yet, he was not satisfied. In an attempt to prove he was ready for even greater power, he accidentally unleashed 'the orb' - a highly volatile fragment of pure Weave, corrupted by Netherese magic, which buried itself in his chest. Cast out by Mystra, humbled by his downfall, he does all he can to prevent the orb's cataclysmic detonation, watching for his chance to get back everything he lost, and more.`,
    icon: './icons/origins/kar_icon.png',
    backgroundId: ECharBg.Outlander,
    defaultRace: '',
    defaultSubrace: ESubraces.ZarielTiefling,
    defaultClass: ECharClasses.Barbarian,
  },
  {
    id: 'ori05',
    name: `Lae'zel`,
    desc: `Crashed down to the Sword Coast from the stars, Lae'zel is a fierce warrior, even by the standards of militant githyanki society. When faced with the possibility of becoming a mind flayer, the monster she has dedicated her life to defeating, she must prove her worth and earn the right to rejoin her people -- if they don't execute her first. Will Lae'zel's strength and determination be enough to prove herself to Queen Vlaakith, or must she walk another path in exile?`,
    icon: './icons/origins/lae_icon.png',
    backgroundId: ECharBg.Soldier,
    defaultRace: '',
    defaultClass: ECharClasses.Fighter,
  },
  {
    id: 'ori06',
    name: 'Shadowheart',
    desc: `A devoted cleric of Shar, goddess of darkness and loss, Shadowheart agreed to have her memories wiped as part of a holy mission. Now its sole survivor, she must deliver a powerful relic back to her kin in order to win Shar's love and have her memories restored – but all the while, she is tormented by strange, painful magic that she struggles to understand.`,
    icon: './icons/origins/sha_icon.png',
    backgroundId: ECharBg.Acolyte,
    defaultRace: '',
    defaultSubrace: ESubraces.HalfHighElf,
    defaultClass: ECharClasses.Cleric,
    defaultSubclass: ESubClasses.Trickery,
  },
  {
    id: 'ori07',
    name: 'Wyll',
    desc: `From a scion of a famed Baldurian house to a life of adventure on the road, Wyll’s life as the monster hunter called the Blade of Frontiers has made him one of the beating hearts of the Sword Coast. While he has done great deeds for the Coast’s people, the source of his power remains secret. The cambion Mizora drew Wyll into a warlock’s pact in a moment with many lives at stake, and cursed him with the duty of hunting her enemies. Mizora only asks Wyll to sacrifice devilish creatures to her, but a cambion’s ambitions are ever fickle, and Wyll wishes to escape the pact before its price grows cruel.`,
    icon: './icons/origins/wyl_icon.png',
    backgroundId: ECharBg.FolkHero,
    defaultRace: '',
    defaultClass: ECharClasses.Warlock,
    defaultSubclass: ESubClasses.Fiend,
  },
  {
    id: 'ori08',
    name: 'The Dark Urge',
    desc: `You remember nothing of your past besides that you walked a path paved with blood. As you venture on, you find yourself inescapably drawn towards unimaginable cruelties. Where do these thoughts come from?`,
    icon: './icons/origins/dur_icon.png',
    backgroundId: ECharBg.HauntedOne,
    defaultRace: '',
    defaultSubrace: ESubraces.WhiteDragon,
    defaultClass: ECharClasses.Sorcerer,
    defaultSubclass: ESubClasses.StormSorcery,
  },
];
