import { IRace } from '../models/dbModels/IRace';
import { EEquipment } from './dbEquipmentProficiencies';
import { ESkills } from './dbSkills';
import { ESubraces } from './dbSubraces';

export enum ERaces {
  Human = 'race01',
  Elf = 'race02',
  Drow = 'race03',
  HalfElf = 'race04',
  HalfOrc = 'race05',
  Halfling = 'race06',
  Dwarf = 'race07',
  Gnome = 'race08',
  Tiefling = 'race09',
  Githyanki = 'race10',
  Dragonborn = 'race11',
}

export const races: IRace[] = [
  {
    id: 'race01',
    icon: './icons/races/Human.png',
    name: 'Human',
    desc: `The most common face in Faerûn, humans are known for their tenacity, creativity, and endless capacity for growth.`,
    equipmentProficiencies: [
      EEquipment.Spears,
      EEquipment.Pikes,
      EEquipment.Halberds,
      EEquipment.Glaives,
      EEquipment.LightArmor,
      EEquipment.Shields,
    ],
    baseSpeed: 9,
  },
  {
    id: 'race02',
    icon: './icons/races/Elf.png',
    name: 'Elf',
    desc: `With ethereal countenances and long lifespans, elves are at home with nature's power, flourishing in light and dark alike.`,
    equipmentProficiencies: [EEquipment.Longswords, EEquipment.Shortswords, EEquipment.Longbows, EEquipment.Shortbows],
    baseSpeed: 9,
    darkvision: 1,
    skillProficiencies: [ESkills.Perception],
    subraces: [ESubraces.HighElf, ESubraces.WoodElf],
  },
  {
    id: 'race03',
    icon: './icons/races/Drow.png',
    name: 'Drow',
    desc: `Driven to the Underdark, most drow have adopted a ruthless pragmatism. While the Lolth-sworn delight in the goddess' evil tenets, the Seldarine reject Her attempt to overthrow the leader of the elven pantheon.`,
    equipmentProficiencies: [EEquipment.Rapiers, EEquipment.Shortswords, EEquipment.HandCrossbows],
    baseSpeed: 9,
    darkvision: 2,
    skillProficiencies: [ESkills.Perception],
    subraces: [ESubraces.LolDrow, ESubraces.SelDrow],
  },
  {
    id: 'race04',
    icon: './icons/races/Half-Elf.png',
    name: 'Half Elf',
    desc: `Curious, ambitious, and versatile, half-elves are welcome everywhere, but struggle without a community to call their own`,
    equipmentProficiencies: [
      EEquipment.Spears,
      EEquipment.Pikes,
      EEquipment.Halberds,
      EEquipment.Glaives,
      EEquipment.LightArmor,
      EEquipment.Shields,
    ],
    baseSpeed: 9,
    darkvision: 1,
    subraces: [ESubraces.HalfHighElf, ESubraces.HalfWoodElf, ESubraces.HalfDrow],
  },
  {
    id: 'race05',
    icon: './icons/races/Half-Orc.png',
    name: 'Half Orc',
    desc: `Creatures of intense emotion, half-orcs are more inclined to act than contemplate - whether the rage burning their bodies compels them to fight, or the love filling their hearts inspires acts of incredible kindness.`,
    baseSpeed: 9,
    darkvision: 1,
    skillProficiencies: [ESkills.Intimidation],
  },
  {
    id: 'race06',
    icon: './icons/races/Halfling.png',
    name: 'Halfling',
    desc: `Small yet capable, halflings prefer the comforts of home and hearth - but their natural luck and dexterity makes them fine adventurers.`,
    baseSpeed: 7.5,
    subraces: [ESubraces.LightHalfling, ESubraces.StrongHalfling],
  },
  {
    id: 'race07',
    icon: './icons/races/Dwarf.png',
    name: 'Dwarf',
    desc: `As durable and unyielding as their homes of stone, dwarves are some of the finest warriors, miners, and smiths of Faerûn`,
    equipmentProficiencies: [
      EEquipment.Battleaxes,
      EEquipment.Handaxes,
      EEquipment.LightHammers,
      EEquipment.Warhammers,
    ],
    baseSpeed: 7.5,
    darkvision: 1,
    subraces: [ESubraces.GoldDwarf, ESubraces.ShieldDwarf, ESubraces.Duergar],
  },
  {
    id: 'race08',
    icon: './icons/races/Gnome.png',
    name: 'Gnome',
    desc: `Small, clever, and energetic, gnomes use their long lives to explore Faerûn's brightest corners and darkest depths.`,
    baseSpeed: 7.5,
    darkvision: 1,
    subraces: [ESubraces.ForestGnome, ESubraces.DeepGnome, ESubraces.RockGnome],
  },
  {
    id: 'race09',
    icon: './icons/races/Tiefling.png',
    name: 'Tiefling',
    desc: `Descended from devils of the Nine Hells, tieflings face constant suspicion in Faerûn. Thankfully, their arcane abilities make them natural survivors.`,
    baseSpeed: 9,
    darkvision: 1,
    subraces: [ESubraces.AsmodTiefling, ESubraces.MephiTiefling, ESubraces.ZarielTiefling],
  },
  {
    id: 'race10',
    icon: './icons/races/Githyanki.png',
    name: 'Githyanki',
    desc: `With a ruthlessness borne from mind flayer enslavement, githyanki ride the Astral Sea atop red dragons, bringing their silver swords and psionic might to bear against any trace of the illithid menace.`,
    equipmentProficiencies: [
      EEquipment.LightArmor,
      EEquipment.MediumArmor,
      EEquipment.Shortswords,
      EEquipment.Longswords,
      EEquipment.Greatswords,
    ],
    baseSpeed: 9,
  },
  {
    id: 'race11',
    icon: './icons/races/Dragonborn.png',
    name: 'Dragonborn',
    desc: `A proud race that values clan and skills above all else. Once enslaved by dragons, they strive to be self-sufficient, not wanting to be beholden to anyone, not even the gods.`,
    baseSpeed: 9,
    subraces: [
      ESubraces.BlackDragon,
      ESubraces.BlueDragon,
      ESubraces.BrassDragon,
      ESubraces.BronzeDragon,
      ESubraces.CopperDragon,
      ESubraces.GoldDragon,
      ESubraces.GreenDragon,
      ESubraces.RedDragon,
      ESubraces.SilverDragon,
      ESubraces.WhiteDragon,
    ],
  },
];
