import { ISpellCasterLevels } from '../models/dbModels/ISpellCasterLevels';

export const dbSpellSlots: ISpellCasterLevels[] = [
  {
    level: 1,
    maxSpellTier: 1,
    level1slots: 2,
    level2slots: 0,
    level3slots: 0,
    level4slots: 0,
    level5slots: 0,
    level6slots: 0,
  },
  {
    level: 2,
    maxSpellTier: 1,
    level1slots: 3,
    level2slots: 0,
    level3slots: 0,
    level4slots: 0,
    level5slots: 0,
    level6slots: 0,
  },
  {
    level: 3,
    maxSpellTier: 2,
    level1slots: 4,
    level2slots: 2,
    level3slots: 0,
    level4slots: 0,
    level5slots: 0,
    level6slots: 0,
  },
  {
    level: 4,
    maxSpellTier: 2,
    level1slots: 4,
    level2slots: 3,
    level3slots: 0,
    level4slots: 0,
    level5slots: 0,
    level6slots: 0,
  },
  {
    level: 5,
    maxSpellTier: 3,
    level1slots: 4,
    level2slots: 3,
    level3slots: 2,
    level4slots: 0,
    level5slots: 0,
    level6slots: 0,
  },
  {
    level: 6,
    maxSpellTier: 3,
    level1slots: 4,
    level2slots: 3,
    level3slots: 3,
    level4slots: 0,
    level5slots: 0,
    level6slots: 0,
  },
  {
    level: 7,
    maxSpellTier: 4,
    level1slots: 4,
    level2slots: 3,
    level3slots: 3,
    level4slots: 1,
    level5slots: 0,
    level6slots: 0,
  },
  {
    level: 8,
    maxSpellTier: 4,
    level1slots: 4,
    level2slots: 3,
    level3slots: 3,
    level4slots: 2,
    level5slots: 0,
    level6slots: 0,
  },
  {
    level: 9,
    maxSpellTier: 5,
    level1slots: 4,
    level2slots: 3,
    level3slots: 3,
    level4slots: 3,
    level5slots: 1,
    level6slots: 0,
  },
  {
    level: 10,
    maxSpellTier: 5,
    level1slots: 4,
    level2slots: 3,
    level3slots: 3,
    level4slots: 3,
    level5slots: 2,
    level6slots: 0,
  },
  {
    level: 11,
    maxSpellTier: 6,
    level1slots: 4,
    level2slots: 3,
    level3slots: 3,
    level4slots: 3,
    level5slots: 2,
    level6slots: 1,
  },
];
